/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   ft_errno.h                                         :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: gufortel <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2018/01/08 17:35:02 by gufortel          #+#    #+#             */
/*   Updated: 2018/03/17 14:37:15 by gufortel         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef FT_ERRNO_H
# define FT_ERRNO_H

# define FT_EPERM     "Operation not permitted"
# define FT_ENOENT       " No such file or directory"
# define FT_ESRCH        " No such process"
# define FT_EINTR        " Interrupted system call"
# define FT_EIO     	 " IO error"
# define FT_ENXIO        " No such device or address"
# define FT_E2BIG        " Argument list too long"
# define FT_ENOEXEC      " Exec format error"
# define FT_EBADF        " Bad file number"
# define FT_ECHILD       " No child processes"
# define FT_EAGAIN       " Try again"
# define FT_ENOMEM       " Out of memory"
# define FT_EACCES       " Permission denied"
# define FT_EFAULT       " Bad address"
# define FT_ENOTBLK      " Block device required"
# define FT_EBUSY        " Device or resource busy"
# define FT_EEXIST       " File exists"
# define FT_EXDEV        " Cross-device link"
# define FT_ENODEV       " No such device"
# define FT_ENOTDIR      " Not a directory"
# define FT_EISDIR       " Is a directory"
# define FT_EINVAL       " Invalid argument"
# define FT_ENFILE       " File table overflow"
# define FT_EMFILE       " Too many open files"
# define FT_ENOTTY       " Not a typewriter"
# define FT_ETXTBSY      " Text file busy"
# define FT_EFBIG        " File too large"
# define FT_ENOSPC       " No space left on device"
# define FT_ESPIPE       " Illegal seek"
# define FT_EROFS        " Read-only file system"
# define FT_EMLINK       " Too many links"
# define FT_EPIPE        " Broken pipe"
# define FT_EDOM         " Math argument out of domain of func"
# define FT_ERANGE       " Math result not representable "
# define FT_FREDEADLK    " Resource deadlock would occur "
# define FT_ENAMETOOLONG " File name too long "
# define FT_ENOLCK       " No record locks available "
# define FT_ENOSYS       " Function not implemented "
# define FT_ENOTEMPTY    " Directory not empty "
# define FT_ELOOP        " Too many symbolic links encountered "
# define FT_EWOULDBLOCK  " Operation would block "
# define FT_ENOMSG       " No message of desired type "
# define FT_EIDRM        " Identifier removed "
# define FT_ECHRNG       " Channel number out of range "
# define FT_EL2NSYNC     " Level 2 not synchronized "
# define FT_EL3HLT       " Level 3 halted "
# define FT_EL3RST       " Level 3 reset "
# define FT_ELNRNG       " Link number out of range "
# define FT_EUNATCH      " Protocol driver not attached "
# define FT_ENOCSI       " No CSI structure available "
# define FT_EL2HLT       " Level 2 halted "
# define FT_EBADE        " Invalid exchange "
# define FT_EBADR        " Invalid request descriptor "
# define FT_EXFULL       " Exchange full "
# define FT_ENOANO       " No anode "
# define FT_EBADRQC      " Invalid request code "
# define FT_EBADSLT      " Invalid slot "
# define FT_EDEADLOCK   	" EDEADLK "
# define FT_EBFONT        " Bad font file format "
# define FT_ENOSTR        " Device not a stream "
# define FT_ENODATA       " No data available "
# define FT_ETIME         " Timer expired "
# define FT_ENOSR         " Out of streams resources "
# define FT_ENONET        " Machine is not on the network "
# define FT_ENOPKG        " Package not installed "
# define FT_EREMOTE       " Object is remote "
# define FT_ENOLINK       " Link has been severed "
# define FT_EADV          " Advertise error "
# define FT_ESRMNT        " Srmount error "
# define FT_ECOMM         " Communication error on send "
# define FT_EPROTO        " Protocol error "
# define FT_EMULTIHOP     " Multihop attempted "
# define FT_EDOTDOT       " RFS specific error "
# define FT_EBADMSG       " Not a data message "
# define FT_EOVERFLOW     " Value too large for defined data type "
# define FT_ENOTUNIQ      " Name not unique on network "
# define FT_EBADFD        " File descriptor in bad state "
# define FT_EREMCHG       " Remote address changed "
# define FT_ELIBACC       " Can not access a needed shared library "
# define FT_ELIBBAD       " Accessing a corrupted shared library "
# define FT_ELIBSCN       " .lib section in a.out corrupted "
# define FT_ELIBMAX       " Attempting to link in too many shared libraries "
# define FT_ELIBEXEC      " Cannot exec a shared library directly "
# define FT_EILSEQ        " Illegal byte sequence "
# define FT_ERESTART      " Interrupted system call should be restarted "
# define FT_ESTRPIPE      " Streams pipe error "
# define FT_EUSERS        " Too many users "
# define FT_ENOTSOCK      " Socket operation on non-socket "
# define FT_EDESTADDRREQ  " Destination address required "
# define FT_EMSGSIZE      " Message too long "
# define FT_EPROTOTYPE    " Protocol wrong type for socket "
# define FT_ENOPROTOOPT   " Protocol not available "
# define FT_EPROTONOSUPPORT  " Protocol not supported "
# define FT_ESOCKTNOSUPPORT  " Socket type not supported "
# define FT_EOPNOTSUPP   " Operation not supported on transport endpoint "
# define FT_EPFNOSUPPORT  " Protocol family not supported "
# define FT_EAFNOSUPPORT  " Address family not supported by protocol "
# define FT_EADDRINUSE    " Address already in use "
# define FT_EADDRNOTAVAIL " Cannot assign requested address "
# define FT_ENETDOWN     " Network is down "
# define FT_ENETUNREACH  " Network is unreachable "
# define FT_ENETRESET    " Network dropped connection because of reset "
# define FT_ECONNABORTED " Software caused connection abort "
# define FT_ECONNRESET   " Connection reset by peer "
# define FT_ENOBUFS      " No buffer space available "
# define FT_EISCONN      " Transport endpoint is already connected "
# define FT_ENOTCONN     " Transport endpoint is not connected "
# define FT_ESHUTDOWN    " Cannot send after transport endpoint shutdown "
# define FT_ETOOMANYREFS " Too many references: cannot splice "
# define FT_ETIMEDOUT    " Connection timed out "
# define FT_ECONNREFUSED " Connection refused "
# define FT_EHOSTDOWN    " Host is down "
# define FT_EHOSTUNREACH " No route to host "
# define FT_EALREADY     " Operation already in progress "
# define FT_EINPROGRESS  " Operation now in progress "
# define FT_ESTALE       " Stale NFS file handle "
# define FT_EUCLEAN      " Structure needs cleaning "
# define FT_ENOTNAM      " Not a XENIX named type file "
# define FT_ENAVAIL      " No XENIX semaphores available "
# define FT_EISNAM       " Is a named type file "
# define FT_EREMOTEIO    " Remote IO error "
# define FT_EDQUOT       " Quota exceeded "
# define FT_ENOMEDIUM    " No medium found "
# define FT_EMEDIUMTYPE  " Wrong medium type "
# define FT_ECANCELED    " Operation Canceled "
# define FT_ENOKEY       " Required key not available "
# define FT_EKEYEXPIRED  " Key has expired "
# define FT_EKEYREVOKED  " Key has been revoked "
# define FT_EKEYREJECTED " Key was rejected by service "
# define FT_EOWNERDEAD   " Owner died "
# define FT_ENOTRECOVERABLE " State not recoverable "

void		argerrno6(char **tab);

#endif
